### ISSUE TITLE
Typo in SummaryWriter?

### ISSUE THREAD

**Issue by arkhodamoradi** [BIGBALLON/pytorch-cifar#2]
Hello,

Should "log_dir" change to "logdir" at here: https://github.com/BIGBALLON/CIFAR-ZOO/blob/master/train.py#L133

**Comment by BIGBALLON** [comment]
Hi, @arkhodamoradi 
the latest commit of tensorboardX use  ``logdir``
https://github.com/lanpa/tensorboardX/blob/e9323109eab780a7444508e95f9d3a49e1f4f59f/tensorboardX/writer.py#L192

while the old version of tensorboardX  used ``log_dir``.
https://github.com/lanpa/tensorboardX/blob/a15266e177c876d654f1062c37d0cf93abb7920f/tensorboardX/writer.py#L246

and I will update my code for the latest commit.

**Comment by arkhodamoradi** [comment]
Thanks for the quick response.
