### ISSUE TITLE
senet improvement

### ISSUE THREAD

**Issue by Ageliss** [BIGBALLON/pytorch-cifar#3]
line 180 of senet.py: 
x = F.avg_pool2d(x, 8, 1) 

will be better fitting all image sizes if changed to 
x = F.avg_pool2d(x, x.size(3), 1)

**Comment by BIGBALLON** [comment]
@Ageliss that's right, would you mind create a merge request? 😸

**Comment by Ageliss** [comment]
> @Ageliss that's right, would you mind create a merge request? 😸

Sure, here u go.
