### ISSUE TITLE
How are the results reported?

### ISSUE THREAD

**Issue by liuwei16** [BIGBALLON/pytorch-cifar#5]
I wonder how the results are reported in your benchmark?
I have had two trials of lenet with the same config, but got best_test_acc of 67.980% and  67.210%, respectively.

**Comment by BIGBALLON** [comment]
@liuwei16  avg of 3 runs, but still have variance(depend on the random init, the GPU, the PyTorch version, etc.)
btw, if you prepare experiments for papers, try to get the results more then 5 runs.
