### ISSUE TITLE
 load() missing 1 required positional argument

### ISSUE THREAD

**Issue by zzh132** [BIGBALLON/pytorch-cifar#8]
def main():
    global args, config, last_epoch, best_prec, writer
    writer = SummaryWriter(log_dir=args.work_path + "/event")

    # read config from yaml file
    with open(args.work_path + "/config.yaml") as f:
        config = yaml.load(f)
**line 168 in train.py, load() missing 1 required positional argument: 'Loader'**

**Comment by neerajkanhere** [comment]
with open(args.work_path + "/config.yaml") as f:
        config = yaml.load(f, Loader=yaml.Loader)
